use `shinsekai-db`;

/* tags */
insert into tags (name, imageFilename) values 
('in blandit', 'product2.png'),
('erat', 'product1.png'),
('vestibulum rutrum', 'product2.png'),
('magnis dis', 'product1.png'),
('etiam justo', 'product3.png'),
('cursus id', 'product3.png'),
('nibh', null),
('vivamus', 'product2.png'),
('orci eget', 'product2.png'),
('tortor', 'product2.png'),
('in', 'product2.png'),
('nunc', 'product3.png'),
('aliquam', 'product1.png'),
('nulla', 'product3.png'),
('varius ut', null);

/* tags_users */
insert into tags_users (tag_id, user_id) values 
(4, 3),
(5, 2),
(2, 4),
(1, 2),
(3, 5),
(3, 5),
(4, 5),
(4, 4),
(4, 5),
(1, 2),
(1, 4),
(1, 1),
(1, 3),
(5, 3),
(5, 4);

/* tags_products */
insert into tags_products (tag_id, product_id) values 
(1, null),
(5, 4),
(4, 1),
(4, 2),
(4, 4),
(2, 4),
(1, 2),
(4, 4),
(1, 1),
(1, 5),
(2, 3),
(5, 4),
(1, 5),
(5, 4),
(4, null);

/* purchasedHistories */
insert into purchasedHistories (user_id) values 
(2),
(5),
(5),
(3),
(4),
(1),
(3),
(4),
(2),
(5),
(5),
(4),
(4),
(4),
(5);

/* purchasedHistories_products */
insert into purchasedHistories_products (purchasedHistory_id, product_id) values 
(1, 3),
(4, 4),
(5, 1),
(1, 2),
(3, 5),
(1, 1),
(3, 3),
(4, 2),
(5, 4),
(5, 5),
(4, 1),
(4, 5),
(2, 4),
(4, 2),
(4, 1);

/* purchaseOrders */
insert into purchaseOrders (user_id) values 
(1),
(3),
(3),
(3),
(1),
(2),
(1),
(5),
(3),
(3),
(3),
(4),
(2),
(2),
(2);

/* purchaseOrders_products */
insert into purchaseOrders_products (purchaseOrder_id, product_id) values 
(5, 4),
(5, 4),
(2, 4),
(5, 3),
(1, 4),
(5, 2),
(4, 1),
(3, 1),
(4, 1),
(1, 4),
(4, 2),
(1, 4),
(2, 2),
(3, 3),
(5, 2);

/* wishLists */
insert into wishLists (user_id) values 
(5),
(5),
(3),
(5),
(1),
(3),
(3),
(5),
(2),
(5),
(2),
(1),
(1),
(3),
(2);

/* wishLists_products */
insert into wishLists_products (wishList_id, product_id) values 
(1, 5),
(2, 5),
(5, 4),
(5, 4),
(2, 5),
(2, 3),
(1, 4),
(5, 2),
(2, 4),
(3, 3),
(3, 2),
(5, 5),
(1, 5),
(4, 1),
(5, 1);

/* viewedHistories */
insert into viewedHistories (user_id) values 
(2),
(5),
(4),
(4),
(1),
(4),
(4),
(3),
(1),
(2),
(1),
(2),
(5),
(5),
(3);

/* viewedHistories_products */
insert into viewedHistories_products (viewedHistory_id, product_id) values 
(4, 1),
(3, 4),
(1, 4),
(3, 2),
(2, 5),
(4, 4),
(3, 5),
(2, 4),
(4, 1),
(2, 5),
(3, 2),
(4, 5),
(1, 1),
(5, 5),
(5, 5);

/* productComments */
insert into productComments (content, user_id, product_id) values 
('eget elit sodales scelerisque mauris sit amet', 5, 3),
('pellentesque quisque porta volutpat erat quisque erat eros viverra', 4, 2),
('condimentum neque sapien placerat ante nulla', 2, 4),
('curae mauris viverra diam vitae quam suspendisse potenti nullam porttitor', 1, 1),
('elementum ligula vehicula consequat morbi a ipsum integer a', 4, 1),
('duis bibendum morbi non quam nec dui luctus rutrum nulla', 3, 4),
('venenatis turpis enim blandit mi in porttitor', 3, 2),
('velit vivamus vel nulla eget eros elementum', 3, 3),
('ipsum primis in faucibus orci luctus et', 1, 1),
('lacus at turpis donec', 3, 4),
('maecenas rhoncus aliquam lacus morbi quis tortor id nulla', 1, 1),
('turpis elementum ligula vehicula consequat morbi a ipsum integer a', 4, 1),
('quisque ut erat curabitur gravida', 1, 1),
('in sagittis dui vel nisl', 4, 2),
('sed ante vivamus tortor duis mattis egestas metus aenean', 1, 3),
('suspendisse potenti in eleifend quam', 3, 5),
('accumsan tortor quis turpis sed ante vivamus tortor duis mattis', 4, 5),
('justo in blandit ultrices', 4, 2),
('donec pharetra magna vestibulum aliquet ultrices erat tortor', 3, 2),
('adipiscing molestie hendrerit at vulputate vitae nisl aenean', 2, 5),
('sodales sed tincidunt eu felis fusce posuere', 1, 5),
('nullam orci pede venenatis non sodales', 2, 2),
('interdum in ante', 1, 4),
('ut volutpat sapien arcu sed augue aliquam erat volutpat', 5, 2),
('justo morbi ut odio cras mi', 4, 2),
('tristique fusce congue diam', 2, 5),
('eget massa tempor convallis nulla neque libero', 4, 2),
('integer ac neque duis bibendum morbi non', 1, 5),
('eleifend pede libero quis orci', 1, 4),
('at velit eu', 2, 1),
('maecenas leo odio condimentum id luctus nec', 4, 2),
('elit proin risus praesent lectus vestibulum', 5, 3),
('erat quisque erat eros viverra eget', 2, 5),
('porttitor lacus at turpis', 5, 5),
('ut dolor morbi vel lectus in', 4, 4),
('amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus', 4, 5),
('vitae consectetuer eget rutrum at lorem integer tincidunt ante vel', 4, 4),
('in congue etiam justo', 3, 4),
('lacinia sapien quis libero nullam sit amet turpis elementum', 5, 1),
('leo odio condimentum id', 3, 3),
('at nunc commodo', 5, 1),
('sit amet eleifend pede libero quis orci', 3, 2),
('rutrum nulla tellus in sagittis dui vel nisl duis', 5, 2),
('sit amet eros suspendisse accumsan', 1, 3),
('diam cras pellentesque volutpat dui', 5, 5);

/* productReviews */
insert into productReviews (points, content, karma, user_id, product_id) values 
(1, 'curae mauris viverra diam vitae quam', 19, 3, 3),
(4, 'vulputate nonummy maecenas tincidunt lacus at velit vivamus', -23, 5, 2),
(10, 'pulvinar nulla pede ullamcorper augue a suscipit nulla elit', 25, 4, 2),
(2, 'eu interdum eu tincidunt in leo maecenas', 21, 5, 3),
(7, 'molestie nibh in lectus pellentesque at nulla suspendisse potenti cras', -13, 5, 1),
(2, 'ac tellus semper interdum', -6, 1, 4),
(9, 'sociis natoque penatibus et magnis dis parturient montes', -8, 4, 4),
(6, 'penatibus et magnis dis parturient', -3, 3, 2),
(3, 'sagittis sapien cum sociis natoque penatibus et', 12, 2, 4),
(7, 'convallis eget eleifend luctus ultricies eu nibh quisque', 3, 4, 1),
(8, 'ante vestibulum ante ipsum primis in faucibus orci luctus et', -10, 3, 4),
(8, 'feugiat non pretium quis lectus suspendisse', 5, 4, 2),
(10, 'erat vestibulum sed', 0, 4, 3),
(4, 'justo in blandit ultrices enim lorem ipsum dolor sit amet', -24, 1, 2),
(5, 'ante vestibulum ante ipsum primis in faucibus orci luctus et', -3, 1, 4),
(10, 'vel accumsan tellus nisi eu orci', -3, 5, 1),
(6, 'eu interdum eu tincidunt in leo maecenas pulvinar lobortis est', -7, 3, 5),
(7, 'enim in tempor turpis nec euismod scelerisque quam turpis adipiscing', -6, 1, 1),
(3, 'faucibus accumsan odio curabitur convallis duis consequat dui', -5, 5, 1),
(1, 'ac leo pellentesque ultrices mattis odio donec vitae', -6, 4, 3),
(6, 'in quis justo', -22, 4, 2),
(5, 'enim blandit mi in porttitor pede justo', -8, 1, 2),
(5, 'consequat morbi a ipsum integer a nibh in quis', 16, 5, 1),
(6, 'ipsum dolor sit amet consectetuer adipiscing elit', 8, 4, 2),
(6, 'nisi venenatis tristique fusce congue', 17, 5, 4),
(1, 'consectetuer adipiscing elit proin', 6, 1, 1),
(6, 'congue diam id ornare imperdiet sapien urna', 16, 3, 2),
(3, 'sapien cursus vestibulum proin', 18, 4, 1),
(4, 'ut tellus nulla ut erat id mauris vulputate elementum', -24, 5, 5),
(7, 'mattis pulvinar nulla pede ullamcorper augue', 6, 4, 4),
(3, 'nec molestie sed justo pellentesque viverra', -14, 3, 5),
(2, 'tellus in sagittis', -7, 5, 5),
(3, 'orci mauris lacinia sapien quis', -11, 2, 5),
(1, 'vitae ipsum aliquam non mauris morbi non', 2, 4, 4),
(5, 'purus eu magna vulputate luctus cum sociis', 20, 4, 2),
(10, 'eget massa tempor convallis nulla neque libero convallis', -21, 2, 5),
(8, 'id ligula suspendisse ornare consequat lectus in est risus auctor', 15, 2, 1),
(4, 'justo maecenas rhoncus aliquam lacus morbi', -24, 2, 1),
(3, 'ac enim in tempor turpis nec euismod', 7, 1, 1),
(1, 'pede libero quis', 22, 2, 4),
(6, 'faucibus orci luctus et ultrices posuere cubilia curae donec', 0, 5, 2),
(10, 'erat curabitur gravida nisi at nibh in hac habitasse platea', -5, 1, 2),
(1, 'suscipit a feugiat et eros', -2, 5, 2),
(3, 'erat id mauris vulputate elementum nullam varius nulla facilisi cras', -24, 2, 2),
(2, 'in ante vestibulum ante ipsum primis in faucibus orci luctus', -22, 5, 4);
